{{- if .Values.background.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "wakingup.fullname" . }}-background
  namespace: {{ .Values.global.namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "wakingup.fullname" . }}-background
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: background
spec:
  replicas: {{ .Values.background.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "wakingup.fullname" . }}-background
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/component: background
  template:
    metadata:
      labels:
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/name: {{ template "wakingup.fullname" . }}-background
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: background
      {{- template "background.annotations" . }}
    spec:
      {{ template "background.affinity" . }}
      {{ template "background.tolerations" . }}
      {{ template "background.nodeselector" . }}
      terminationGracePeriodSeconds: {{ .Values.background.terminationGracePeriodSeconds | default 300 }}
      containers:
        - name: wakingup-background
          image: {{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: ["yarn"]
          args:
            - start-background
          {{- if .Values.background.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: {{ .Values.background.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
           {{- end }}
          {{- if .Values.background.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: {{ .Values.background.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 3
          {{- end }}
          {{ template "background.resources" . }}
          envFrom:
          - secretRef:
          {{- if .Values.global.externalSecrets.enabled }}
              name: {{ .Release.Name }}-background
          {{ else }}
              name: {{ .Values.background.varsSecretName | default "null" | quote }}
          {{- end }}
          - secretRef:
          {{- if .Values.global.externalSecrets.enabled }}
              name: shared
          {{ else }}
              name: shared
          {{- end }}
         {{ template "background.mounts" . }}
         {{ template "background.volumes" . }}
{{- end }}
