{{- if .Values.cron.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "wakingup.fullname" . }}-cron
  namespace: {{ .Values.global.namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "wakingup.fullname" . }}-cron
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: cron
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "wakingup.fullname" . }}-cron
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/component: cron
  template:
    metadata:
      labels:
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/name: {{ template "wakingup.fullname" . }}-cron
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/component: cron
      {{- template "cron.annotations" . }}
    spec:
      {{ template "cron.affinity" . }}
      {{ template "cron.tolerations" . }}
      {{ template "cron.nodeselector" . }}
      terminationGracePeriodSeconds: {{ .Values.cron.terminationGracePeriodSeconds | default 300 }}
      containers:
        - name: wakingup-cron
          image: {{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          command: ["yarn"]
          args:
            - start-cron
          {{- if .Values.cron.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: {{ .Values.cron.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 5
           {{- end }}
          {{- if .Values.cron.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /healthz
              port: {{ .Values.cron.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 3
          {{- end }}
          {{ template "cron.resources" . }}
          envFrom:
          - secretRef:
          {{- if .Values.global.externalSecrets.enabled }}
              name: {{ .Release.Name }}-cron
          {{ else }}
              name: {{ .Values.cron.varsSecretName | default "null" | quote }}
          {{- end }}
          - secretRef:
          {{- if .Values.global.externalSecrets.enabled }}
              name: shared
          {{ else }}
              name: shared
          {{- end }}
         {{ template "cron.mounts" . }}
         {{ template "cron.volumes" . }}
{{- end }}
