{{ if .Values.global.migrations.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: wakingup-api-db-migrations
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "1"
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db-migrations
        image: {{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}
        command: [ "yarn", "db:migrate"]
        resources:
          requests:
            memory: 2Gi
            cpu: 1
          limits:
            memory: 2Gi
            cpu: 2
        envFrom:
          - secretRef:
          {{- if .Values.global.externalSecrets.enabled }}
              name: {{ .Release.Name }}-api
          {{ else }}
              name: {{ .Values.api.varsSecretName | default "null" | quote }}
          {{- end }}
          - secretRef:
          {{- if .Values.global.externalSecrets.enabled }}
              name: shared
          {{ else }}
              name: shared
          {{- end }}
{{ end }}