{{- if and .Values.webhooks.ingress.enabled .Values.webhooks.enabled -}}
{{- $serviceName := include "wakingup.fullname" . -}}
{{- $servicePort := .Values.webhooks.service.port -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "wakingup.fullname" . }}-webhooks
  namespace: {{ .Values.global.namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "wakingup.fullname" . }}-webhooks
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- template "webhooks.ingress.annotations" . }}
spec:
  ingressClassName: {{ .Values.webhooks.ingress.ingressClassName }}
{{- if .Values.webhooks.ingress.tls }}
  tls:
  {{- range .Values.webhooks.ingress.tls.hosts }}
    - hosts:
        - {{ . | quote }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.webhooks.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range (.paths | default (list "/")) }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              serviceName: {{ $serviceName }}-webhooks-svc
              servicePort: {{ $servicePort }}
        {{- end }}
  {{- end }}
{{- end }}