{{- if and .Values.webhooks.enabled .Values.webhooks.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "wakingup.fullname" . }}-webhooks-svc
  namespace: {{ .Values.global.namespace }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "wakingup.fullname" . }}-webhooks
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/component: webhooks
spec:
  ports:
  - port: {{ .Values.webhooks.service.port }}
    targetPort: {{ .Values.webhooks.service.targetPort }}
  selector:
    app.kubernetes.io/name: {{ template "wakingup.fullname" . }}-webhooks
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: webhooks
{{- end }}