name: CI

on: 
  push:
    branches: 
      - test
jobs:
  ci:
    name: 'kaniko'
    runs-on: ubuntu-latest #[self-hosted, linux, X64]
    container:
      image: gcr.io/kaniko-project/executor:debug-v1.0.0
      options: --entrypoint "sh"
    steps:
      - uses: actions/checkout@v1
        
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1
          
      - name: Generate a config.json
        run: |
          mkdir -p /kaniko/.docker
          echo "{\"credsStore\":\"ecr-login\",\"credHelpers\":{\"$AWS_ACCOUNT_ID.dkr.ecr.region.amazonaws.com\":\"ecr-login\"}}" > /kaniko/.docker/config.json         
    
      - name: test
        run:
           /kaniko/executor --force --context=$GITHUB_WORKSPACE --dockerfile=$GITHUB_WORKSPACE/Dockerfile --destination=$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/kaniko-test:latest --cache=true --cache-repo=$AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/kaniko-test


         # /kaniko/executor --context=test --dockerfile=test/Dockerfile --destination=test --cache=true --cache-repo=556020183454.dkr.ecr.us-east-1.amazonaws.com/kaniko-test'
          
   
