name: CI

on: 
  push:
    branches: 
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Build backend
        uses: docker://gcr.io/kaniko-project/executor:v1.6.0-debug
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /kaniko/config.json
        with:
          entrypoint: echo "hi"          
      
      - uses: craftech-io/slack-action@v1
        if: always()
