name: CI

on: 
  push:
    branches: 
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install, and test
        run: |
          npm install
          npm test
        env:
          CI: true
      
      - uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: http://culquier.com
        if: always()
