name: CI

on:
  push:
    branches:
      - master
      - if-master
jobs:
  ci:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Deploy production
        if: github.ref == 'refs/heads/if-master'
        uses: craftech-io/eks-helm-deploy-action@v0.0.4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          cluster-name: ${{ secrets.CLUSTER_NAME }}
          config-files: api/deploy/chart/values-dev.yaml
          chart-path: api/deploy/chart
          namespace: test
          values: global.image.tag=${{ github.sha }}
          name: wakingup-api-v2