name: CI

on: 
  push:
    branches: 
      - test
jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: ubuntu
    steps:
      - uses: actions/checkout@v1
        
#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1
          
      - name: Generate a config.json
        run: |
          mkdir -p /kaniko/.docker
          echo "{\"credsStore\":\"ecr-login\",\"credHelpers\":{\"$AWS_ACCOUNT_ID.dkr.ecr.region.amazonaws.com\":\"ecr-login\"}}" > /kaniko/.docker/config.json         
      
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v2
        with:
          name: config.json
          path: /kaniko/.docker/config.json
  
  validate:
    name: 'kaniko'
    runs-on: ubuntu-latest #[self-hosted, linux, X64]
    container:
      image: gcr.io/kaniko-project/executor:latest
      options: --entrypoint "/bin/bah"

    steps:
     - name: Download math result for job 2
       uses: actions/download-artifact@v2
       with:
        name: config.json
        path: /kaniko/.docker/config.json
    
     - name: Download math result for job 2
       run:
         /kaniko/executor --context=test --dockerfile=test/Dockerfile --destination=test --cache=true --cache-repo=test'     
