name: CI

on:
  push:
    branches:
      - login-ecr
jobs:
  build:
    name: 'build'
    runs-on: ubuntu-latest
    outputs:
      token: ${{ steps.ecr-credentials.outputs.token }}
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          
      - name: Get AWS ECR credentials
        id: ecr-credentials
        run: |
          export TOKEN=$(aws ecr get-login-password --region us-west-2)
          echo $TOKEN
          echo ::set-output name=token::$TOKEN
          
      - name: Build, Tag, Push
        uses: whoan/docker-build-with-cache-action@v5
        with:
          registry: 103144140553.dkr.ecr.us-west-2.amazonaws.com
          image_name: build-test
          image_tag: test-ecr-login


  # Label of the container job
  test-job:
    needs: [build]
    if: success()
    # Containers must run in Linux based operating systems
    runs-on: [self-hosted, linux, X64]
    # Docker Hub image that `test-job` executes in
    container:
      image: 103144140553.dkr.ecr.us-west-2.amazonaws.com:${{ github.sha }}
      credentials:
        username: AWS
        password: ${{ needs.build.outputs.token }}

    steps:
      
      - name: Check out repository code
        run:
          echo ${{ needs.build.outputs.token }}

          
